apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer
  selector:
    app: sample-app     # IMPORTANT: selects both v1 + v2
  ports:
  - port: 80
    targetPort: 80
