apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    app: guestbook
spec:
  type: LoadBalancer   # ✅ Creates AWS ELB for external access
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: guestbook
